### ISSUE TITLE
polar angle = 'Elevation'?

### ISSUE THREAD

**Issue by chris-hld** [spatialaudio/sfa-numpy#15]
https://github.com/spatialaudio/sfa-numpy/blob/1f798b9d89f6af1349f5b4fc013f671f273d136d/micarray/modal/angular.py#L201

Could you please clarify the term elevation here?
I know that Rafaely uses this term for the polar angle / colatitude, however, pretty much everybody else uses elevation for latitude.

In other words, where is the north pole?

**Comment by ghost** [comment]
At 0.
You're right, 'colatitude' would be more proper.

**Comment by chris-hld** [comment]
Perfect, thanks!

**Comment by ghost** [comment]
Reopened. This is indeed a case of bad naming and/or documentation.

**Comment by chris-hld** [comment]
The AES69-2015 and therefore SOFA specifies theta as elevation https://www.sofaconventions.org/mediawiki/index.php/SOFA_specifications, ISO 80000-2:2009 as polar angle.
However, the AES standard says:

> The applied spherical coordinate system does not correspond to ISO 80000-2:2009, which defines the spherical coordinate system with the ‘zenith’ angle \delta measured from the positive z-axis. The zenith is the complement of elevation, that is \theta = 90° − \delta. AES69 implements the elevation \theta (and not the zenith \delta) that is typically used in virtual audio applications and perceptual studies.

This is such a mess...
I (personally) would say, if something is not elevated (=0), it is in front of me.
Maybe using the term 'polar angle' is more precise in this case?

**Comment by ghost** [comment]
SciPy seems to use `[0, 2pi) x [0, pi]` coordinates exclusively, so I'd go with that.
Unfortunately naming conventions [are](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.sph_harm.html) [all](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.RectSphereBivariateSpline.html) [over](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.SmoothSphereBivariateSpline.html).

"polar angle" is already used for the unit circle in `modal.angular.grid_equal_polar_angle` and `modal.angular.cht_matrix`.

"zenith" or "colatitude" seem to be unambiguous names for the `[0, pi]` angle. 
Would `colat` be a reasonable parameter name?

**Comment by chris-hld** [comment]
Yes, I think this is reasonable.
